version: "3"

dotenv: [.env]

tasks:
  build:
    sources:
      - "**/*.go"
    generates:
      - ./dist/app.exe
    cmd: go build -tags dev -o dist/app.exe

  dev:
    deps:
      - build
    cmd: ./dist/app.exe

  gen:template:
    sources:
      - "templates/**/*.templ"
      - "templates/*.templ"
    cmds:
      - go tool templ generate -path templates/

  gen:
    cmds:
      - sqlc generate
