version: "3"

dotenv: [ .env ]

tasks:
  build:
    sources:
      - 'go.mod'
      - "templates/**/*.templ"
      - "templates/*.templ"
      - "**/*.go"
      - exclude: "templates/*.go"
    generates:
      - ./dist/app.exe
    cmds:
      - go tool templ generate -path templates/
      - go build -tags dev -o dist/app.exe

  migrate:
    dotenv:
      - .env
    cmds:
      - migrate -database {{ .PG_DSN }} -path db/migrations force 1
      - migrate -database {{ .PG_DSN }} -path db/migrations -verbose up

  new-migrate:
    - migrate create -ext sql -dir db/migrations -seq {{ .NAME }}


  dev:
    deps:
      - build
    cmd: ./dist/app.exe

  format:
    cmds:
      - gofmt -s -w .
      - go tool templ fmt templates/

  gen:template:
    sources:
      - "templates/**/*.templ"
      - "templates/*.templ"
    cmds:
      - go tool templ generate -path templates/

  gen:
    cmds:
      - sqlc generate
