version: "3"

dotenv: [.env]

tasks:
  build:
    sources:
      - 'go.mod'
      - "templates/**/*.templ"
      - "templates/*.templ"
      - "**/*.go"
      - exclude: "templates/*.go"
    generates:
      - ./dist/app.exe
    cmds:
      - go tool templ generate -path templates/
      - go build -tags dev -o dist/app.exe

  dev:
    deps:
      - build
    cmd: ./dist/app.exe

  format:
    cmds:
      - gofmt -s -w .
      - go tool templ fmt templates/

  gen:template:
    sources:
      - "templates/**/*.templ"
      - "templates/*.templ"
    cmds:
      - go tool templ generate -path templates/

  py:
    dotenv:
      - .env
    cmds:
      - watchexec -r -e py --shell=none -- uvicorn server.app:app --no-access-log --port=4562

  gen:
    cmds:
      - sqlc generate
