version: 3

tasks:
  default:
    - ruff check . --fix --fixable=ALL
    - black .
    - mypy .

  dev:
    dotenv:
      - .env
    cmds:
      - watchexec -r -e py -- uvicorn server.app:app --no-access-log

  build:
    - python scripts/build-common.py
    - python scripts/fetch-static-files.py
