version: "3"

dotenv: [.env]

tasks:
  migrate:
    dotenv:
      - .env
    cmds:
      - migrate -database {{ .PG_DSN }} -path db/migrations force 1
      - migrate -database {{ .PG_DSN }} -path db/migrations -verbose up

  new-migrate:
    - migrate create -ext sql -dir db/migrations -seq {{ .NAME }}

  build:
    sources:
      - "go.mod"
      - "*.go"
    generates:
      - ./dist/app.exe
    cmds:
      - go build -tags dev -o dist/app.exe

  dev:
    cmds:
      - go build -tags dev -o dist/app.exe
      - ./dist/app.exe

  format:
    cmds:
      - gofmt -s -w .
      - templ fmt templates/

  gen:template:
    sources:
      - "templates/*.templ"
    generates:
      - "templates/*.go"
    cmds:
      - templ generate -path templates/

  gen:
    cmds:
      - sqlc generate

  watch:template:
    cmd: watchexec --shell=none -e templ -w . -r -- task gen:template --force

  watch:dev:
    cmd: watchexec --shell=none -e go,mod -w . -w templates -r -- task dev

  dump-schema:
    - pg_dump --schema-only -d {{ .PG_DSN }} > db/schema.sql
