version: 3

tasks:
  default:
    - ruff check . --fix --fixable=ALL
    - black .
    - mypy .

  dev:
    dotenv:
      - .env
    cmds:
      - watchexec -r -e py -- uvicorn server.app:app --no-access-log

  run:
    dotenv: [ .env ]
    cmds:
      - python {{.CLI_ARGS}}

  lock:no-cache:
    cmds:
      - poetry lock --no-update --no-cache
      - dos2unix.exe poetry.lock
      - poetry install --sync

  update:
    cmds:
      - poetry update
      - dos2unix.exe poetry.lock
      - poetry install --sync

  lock:
    cmds:
      - poetry lock --no-update
      - dos2unix.exe poetry.lock
      - poetry install --sync

  sync: 'poetry install --sync{{ if eq OS "linux" }} --only main{{end}}'
