version: 3

tasks:
  default:
    - ruff check . --fix --fixable=ALL
    - black .
    - mypy .

  server:
    cmds:
      - watchfiles -target-type=command --filter python 'uvicorn server.app:app --env-file .env --no-access-log' server

  run:
    dotenv: [ .env ]
    cmds:
      - python {{.CLI_ARGS}}

  lock:no-cache:
    cmds:
      - poetry lock --no-update --no-cache
      - dos2unix.exe poetry.lock
      - poetry install --sync

  update:
    cmds:
      - poetry update
      - dos2unix.exe poetry.lock
      - poetry install --sync

  lock:
    cmds:
      - poetry lock --no-update
      - dos2unix.exe poetry.lock
      - poetry install --sync

  sync: 'poetry install --sync{{ if eq OS "linux" }} --only main{{end}}'
