// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type EditSuggestion struct {
	ID        uuid.UUID
	PatchID   uuid.UUID
	PatchType string
	Text      string
	FromUser  int32
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type EpisodePatch struct {
	ID                  uuid.UUID
	EpisodeID           int32
	State               int32
	FromUserID          int32
	WikiUserID          int32
	Reason              string
	OriginalName        pgtype.Text
	Name                pgtype.Text
	OriginalNameCn      pgtype.Text
	NameCn              pgtype.Text
	OriginalDuration    pgtype.Text
	Duration            pgtype.Text
	OriginalAirdate     pgtype.Text
	Airdate             pgtype.Text
	OriginalDescription pgtype.Text
	Description         pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	RejectReason        string
	SubjectID           int32
	CommentsCount       int32
	PatchDesc           string
	Ep                  pgtype.Int4
	NumID               int64
}

type PatchTablesMigration struct {
	Version int64
	Dirty   bool
}

type PatchUser struct {
	UserID   int32
	Username string
	Nickname string
}

type SubjectPatch struct {
	ID               uuid.UUID
	SubjectID        int32
	State            int32
	FromUserID       int32
	WikiUserID       int32
	Reason           string
	Name             pgtype.Text
	OriginalName     string
	Infobox          pgtype.Text
	OriginalInfobox  pgtype.Text
	Summary          pgtype.Text
	OriginalSummary  pgtype.Text
	Nsfw             pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	RejectReason     string
	SubjectType      int64
	CommentsCount    int32
	PatchDesc        string
	OriginalPlatform pgtype.Int4
	Platform         pgtype.Int4
	// 1 for update 2 for create
	Action pgtype.Int4
	NumID  int64
}
