name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2
      - run: python -m pytest -rva
