name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sqlc:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: pg-user
          POSTGRES_PASSWORD: pg-password
          POSTGRES_DB: db_test
        ports:
          # Maps tcp port 5432 on service container to the host
          - '5432:5432'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "true"

      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.29.0'

      - run: sqlc diff

      - run: sqlc vet
        env:
          PG_DSN: postgresql://pg-user:pg-password@postgres:5432/db_test?sslmode=disable
