name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sqlc:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "true"

      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.29.0'

      - run: sqlc vet
        env:
          POSTGRESQL_SERVER_URI: postgres://postgres:postgres@postgres:5432/db_test?sslmode=disable
