name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "true"

      - uses: trim21/actions/setup-go@master
        with:
          cache-namespace: test

      - uses: sigoden/install-binary@7eb4b088aedf19fe9b2bc6c6bbdc12379ffb355c # v1
        with:
          repo: gotestyourself/gotestsum
          tag: v1.12.1

      - run: gotestsum --hide-summary=skipped --format-hide-empty-pkg

  sqlc:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pg-user
          POSTGRES_PASSWORD: pg-password
          POSTGRES_DB: db_test
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "true"

      - uses: sqlc-dev/setup-sqlc@7f68db1d47e070cf70f6033f13cdecce995f520f # v3
        with:
          sqlc-version: '1.29.0'

      - run: env

      - run: sudo apt install postgresql-client -y
      - run: psql postgresql://pg-user:pg-password@127.0.0.1:5432/db_test?sslmode=disable -a -f db/schema.sql

      - run: sqlc diff
        env:
          PG_DSN: postgresql://pg-user:pg-password@127.0.0.1:5432/db_test?sslmode=disable

      - run: sqlc vet
        env:
          PG_DSN: postgresql://pg-user:pg-password@127.0.0.1:5432/db_test?sslmode=disable
