name: review

on:
  pull_request_target:
    branches:
      - master
      - daemon

jobs:
  lock:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: echo 1
